/**
 * Seed MongoDB with data from client/src/data JSON files.
 * Backend generates all ids (_id); relations use ObjectIds.
 * Run from server folder: npm run seed
 */
import * as fs from 'fs';
import * as path from 'path';
import dotenv from 'dotenv';
import mongoose from 'mongoose';
import { Category } from '../src/model/Category';
import { Group } from '../src/model/Group';
import { Topic } from '../src/model/Topic';
import { Question } from '../src/model/Question';

dotenv.config({ path: path.join(__dirname, '..', '.env') });

const DATA_DIR = path.join(__dirname, '..', '..', 'client', 'src', 'data');

function loadJson<T>(filename: string): T {
  const filePath = path.join(DATA_DIR, filename);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Data file not found: ${filePath}`);
  }
  const raw = fs.readFileSync(filePath, 'utf-8');
  return JSON.parse(raw) as T;
}

type CategoryJson = { id: string; name: string; title: string; icon: string };
type GroupJson = { id: string; categoryId: string; name: string; title: string; icon: string };
type TopicJson = { id: string; groupId: string; categoryId: string; name: string; title: string };
type QuestionJson = {
  id: string;
  categoryId: string;
  groupId: string;
  topicId: string;
  question: string;
  answer: string;
};

async function seed() {
  const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/interviewprep';
  await mongoose.connect(uri);
  console.log('MongoDB connected');

  const categoriesJson = loadJson<CategoryJson[]>('categories.json');
  const groupsJson = loadJson<GroupJson[]>('groups.json');
  const topicsJson = loadJson<TopicJson[]>('topics.json');
  const questionsJson = loadJson<QuestionJson[]>('questions.json');

  // Drop collections so old indexes (e.g. id_1) are removed; then insert recreates with current schema
  await Category.collection.drop().catch(() => {});
  await Group.collection.drop().catch(() => {});
  await Topic.collection.drop().catch(() => {});
  await Question.collection.drop().catch(() => {});

  // Insert categories (no id – backend generates _id)
  const categoryDocs = await Category.insertMany(
    categoriesJson.map((c) => ({ name: c.name, title: c.title, icon: c.icon }))
  );
  const categoryIdMap = new Map<string, mongoose.Types.ObjectId>();
  categoryDocs.forEach((doc, i) => {
    categoryIdMap.set(categoriesJson[i].id, doc._id);
  });

  // Insert groups (categoryId = new ObjectId from map)
  const groupDocs = await Group.insertMany(
    groupsJson.map((g) => ({
      categoryId: categoryIdMap.get(g.categoryId)!,
      name: g.name,
      title: g.title,
      icon: g.icon,
    }))
  );
  const groupIdMap = new Map<string, mongoose.Types.ObjectId>();
  groupDocs.forEach((doc, i) => {
    groupIdMap.set(groupsJson[i].id, doc._id);
  });

  // Insert topics
  const topicDocs = await Topic.insertMany(
    topicsJson.map((t) => ({
      groupId: groupIdMap.get(t.groupId)!,
      categoryId: categoryIdMap.get(t.categoryId)!,
      name: t.name,
      title: t.title,
    }))
  );
  const topicIdMap = new Map<string, mongoose.Types.ObjectId>();
  topicDocs.forEach((doc, i) => {
    topicIdMap.set(topicsJson[i].id, doc._id);
  });

  // Insert questions
  await Question.insertMany(
    questionsJson.map((q) => ({
      categoryId: categoryIdMap.get(q.categoryId)!,
      groupId: groupIdMap.get(q.groupId)!,
      topicId: topicIdMap.get(q.topicId)!,
      question: q.question,
      answer: q.answer,
    }))
  );

  console.log(
    `Seeded: ${categoriesJson.length} categories, ${groupsJson.length} groups, ${topicsJson.length} topics, ${questionsJson.length} questions (ids generated by backend)`
  );
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
